version: "3.3"

services:
  traefik:
    image: "traefik:v3.0"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - CF_API_EMAIL=${CF_API_EMAIL}
    volumes:
      - /etc/localtime:/etc/localtime:ro # config localtime
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #===================================================
      # this file using traefik.yml
      #===================================================
      - /tmp/acme.json:/letsencrypt/acme.json
      - ./traefik.yml:/etc/traefik/traefik.yml
    networks:
      - traefik-net
      - frontend-net
    labels:
      - "traefik.enable=true"
      #===================================================
      # router configuration
      #===================================================
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.traefik.duongdx.com`)"
      - "traefik.http.routers.dashboard.entrypoints=webSecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      # router <---> middleware configuration
      - "traefik.http.routers.dashboard.middlewares=traefik-auth,traefik-compress,traefik-errorpages"
      #===================================================
      # tls configuration
      #===================================================
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=my-resolver"
      #===================================================
      # middlewares configuration
      #===================================================
      # echo $(htpasswd -nB duongdx) | sed -e s/\\$/\\$\\$/g
      # user_1: duongdx
      # password_1: xxxxxx
      # user_2: xuanduong
      # password_1: xxxxxx
      - "traefik.http.middlewares.traefik-auth.basicauth.users=duongdx:$$2y$$05$$G01EAMot6n2rmushO6v28.auOqg9ayoh7qTK13QDwIuHkwyV/brhG,xuanduong:$$2y$$05$$Yr7IfuW7caBgdMwNPg54MOZB6e38pTB7rv18txQHkotQsBl9OfAUO"
      # compress config: Enable gzip compression
      - "traefik.http.middlewares.traefik-compress.compress=true"
      # Error Pages Middleware
      - "traefik.http.middlewares.traefik-errorpages.errors.status=400-599"
      - "traefik.http.middlewares.traefik-errorpages.errors.service=error" # invoke error services
      - "traefik.http.middlewares.traefik-errorpages.errors.query=/{status}.html"

  frontend:
    image: "duong1200798/socket_app_react:latest"
    networks:
      - frontend-net
    labels:
      - "traefik.enable=true"
      #===================================================
      # router configuration
      #===================================================
      - "traefik.http.routers.frontend.rule=Host(`react.duongdx.com`)"
      - "traefik.http.routers.frontend.entrypoints=webSecure"
      - "traefik.http.routers.frontend.service=frontend"
      # router <---> middleware configuration
      - "traefik.http.routers.frontend.middlewares=frontend-compress"

      #===================================================
      # service configuration
      #===================================================
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"

      #===================================================
      # tls configuration
      #===================================================
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=my-resolver"

      #===================================================
      # middlewares configuration
      #===================================================
      # compress config: Enable gzip compression
      - "traefik.http.middlewares.frontend-compress.compress=true"

  portainer:
    image: portainer/portainer-ce:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - traefik-net
      - frontend-net  # Added Portainer to frontend-net network
    deploy:
      placement:
        constraints:
          - node.role == manager
    labels:
      - "traefik.enable=true"
      #===================================================
      # router configuration
      #===================================================
      - "traefik.http.routers.portainer.rule=Host(`portainer.duongdx.com`)"
      - "traefik.http.routers.portainer.entrypoints=webSecure"
      - "traefik.http.routers.portainer.service=portainer"
      #===================================================
      # service configuration
      #===================================================
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      #===================================================
      # tls configuration
      #===================================================
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=my-resolver"
      #===================================================
      # middlewares configuration
      #
      # compress config: Enable gzip compression
      #===================================================
      - "traefik.http.middlewares.traefik-compress.compress=true"
    ports:
      - "9000:9000"

  # Error Page service
  error:
    image: guillaumebriday/traefik-custom-error-pages
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.error.rule=Host(`error.duongdx.com`)"
      - "traefik.http.routers.error.service=error"
      - "traefik.http.services.error.loadbalancer.server.port=80"
      - "traefik.http.routers.error.entrypoints=webSecure"
# if traefik don't have access to this network => error
networks:
  traefik-net:
    driver: overlay

  frontend-net:
    driver: overlay

volumes:
  portainer_data:
