################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  #
  #
  dashboard: true
  insecure: true
################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
################################################################
# EntryPoints:
################################################################
entryPoints:
  web:
    address: ":80"
    # http:
      # redirections:
      #   entryPoint:
      #     to: webSecure
      #     scheme: https
      #     permanent: true

  webSecure:
    address: ":443"
    # http:
    #   tls:
    #     certResolver: my-resolver
    #     domains:
    #       - main: "duongdx.com"
    #         sans:
    #           - "*.duongdx.com"

################################################################
# Traefik Logging
################################################################
log:
  level: DEBUG

################################################################
# Traefik http
################################################################
certificatesResolvers:
  my-resolver:
    acme:
      email: xuanduong.kma@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
      # config DNS Challenge: when new container created traefik will create new dns record in cloudflar
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - 1.1.1.1:53
          - 1.0.0.1:53