
- name: install docker
  hosts: all
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: passing manifests file
      copy:
        src: ./traefik
        dest: /tmp/
        owner: "{{ ansible_user }}"

    - name: acme.json
      file:
        dest: /tmp/acme.json
        state: touch
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0600

   # Start: install container runtime
    - name: Uninstall old versions
      apt:
        name:
          - docker.io
          - docker-compose
          - docker-compose-v2
          - docker-doc
          - podman-docker
        state: absent

    - name: Install prerequisite for container run time
      apt:
        name:
          - curl
          - vim
          - gpg
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: latest
        update_cache: yes # this option is the same 'apt-get update'

    - name: make directory for saving key
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        keyring: "/etc/apt/keyrings/docker.gpg"
        state: present
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"

    - name: Add Docker Repository
      lineinfile:
        path: "/etc/apt/sources.list.d/docker.list"
        line: "deb [arch={{ architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} \
         {{ ansible_distribution_release }} stable"
        create: yes

    - name: Update apt and install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
        state: present
        update_cache: true

    - name: enabled && restart docker
      service:
        name: docker
        state: restarted
        enabled: true

    - name: adding existing user '{{ ansible_user }}' to group docker
      user:
        name: '{{ ansible_user }}'
        groups: docker
        append: yes

    # create host environment
    - name: Add environment variable to .bashrc
      lineinfile:
        path: /home/{{ ansible_user }}/.bashrc
        line: "export CF_DNS_API_TOKEN={{ cloudflare_api_token }}"
        create: yes

    - name: Add environment variable to .profile
      lineinfile:
        path: /home/{{ ansible_user }}/.profile
        line: "export CF_DNS_API_TOKEN={{ cloudflare_api_token }}"
        create: yes

    - name: Add environment variable to .bashrc
      lineinfile:
        path: /home/{{ ansible_user }}/.bashrc
        line: "export CF_API_EMAIL={{ cloudflare_api_email }}"
        create: yes

    - name: Add environment variable to .profile
      lineinfile:
        path: /home/{{ ansible_user }}/.profile
        line: "export CF_API_EMAIL={{ cloudflare_api_email }}"
        create: yes

    # cloudflare create new dns record
    - name: Create DNS records
      community.general.cloudflare_dns:
          zone: "duongdx.com"
          type: "A"
          record: "*"
          content: "{{ ansible_host }}"
          proxied: "false"
          ttl: "300"
          api_token: "{{ cloudflare_api_token }}"
          state: present
