version: "3.3"

services:

  frontend:
    image: "duong1200798/socket_app_react:latest"
    ports:
      - 8080:8080
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - CF_API_EMAIL=${CF_API_EMAIL}
