version: "3.3"

services:

  traefik:
    image: "traefik:v3.0"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro # config localtime
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #####################################
      # this file using traefik.yml
      #####################################
      - ./traefik.yml:/etc/traefik/traefik.yml
    labels:
      - "traefik.enable=true"

  whoami:
    image: "traefik/whoami"
    # container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.routers.whoami.service=whoami"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
