################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  #
  #
  dashboard: true
  insecure: true
################################################################
# Docker configuration backend
################################################################
providers:
  docker: 
    watch: true
    exposedByDefault: false
################################################################
# EntryPoints:
################################################################
entryPoints:
  web:
    address: ":80"
  webSecure:
    address: ":443"

################################################################
# Traefik Logging
################################################################
log:
  level: INFO